# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /xavier_ssd/Dev/RANE_SOFTWARE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /xavier_ssd/Dev/RANE_SOFTWARE

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /xavier_ssd/Dev/RANE_SOFTWARE/CMakeFiles /xavier_ssd/Dev/RANE_SOFTWARE/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /xavier_ssd/Dev/RANE_SOFTWARE/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named prog_lidar

# Build rule for target.
prog_lidar: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prog_lidar
.PHONY : prog_lidar

# fast build rule for target.
prog_lidar/fast:
	$(MAKE) -f CMakeFiles/prog_lidar.dir/build.make CMakeFiles/prog_lidar.dir/build
.PHONY : prog_lidar/fast

#=============================================================================
# Target rules for targets named prog_com_server

# Build rule for target.
prog_com_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prog_com_server
.PHONY : prog_com_server

# fast build rule for target.
prog_com_server/fast:
	$(MAKE) -f CMakeFiles/prog_com_server.dir/build.make CMakeFiles/prog_com_server.dir/build
.PHONY : prog_com_server/fast

#=============================================================================
# Target rules for targets named prog_global_path

# Build rule for target.
prog_global_path: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prog_global_path
.PHONY : prog_global_path

# fast build rule for target.
prog_global_path/fast:
	$(MAKE) -f CMakeFiles/prog_global_path.dir/build.make CMakeFiles/prog_global_path.dir/build
.PHONY : prog_global_path/fast

#=============================================================================
# Target rules for targets named exempleA

# Build rule for target.
exempleA: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exempleA
.PHONY : exempleA

# fast build rule for target.
exempleA/fast:
	$(MAKE) -f CMakeFiles/exempleA.dir/build.make CMakeFiles/exempleA.dir/build
.PHONY : exempleA/fast

#=============================================================================
# Target rules for targets named prog_data_manager

# Build rule for target.
prog_data_manager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prog_data_manager
.PHONY : prog_data_manager

# fast build rule for target.
prog_data_manager/fast:
	$(MAKE) -f CMakeFiles/prog_data_manager.dir/build.make CMakeFiles/prog_data_manager.dir/build
.PHONY : prog_data_manager/fast

#=============================================================================
# Target rules for targets named exempleB

# Build rule for target.
exempleB: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exempleB
.PHONY : exempleB

# fast build rule for target.
exempleB/fast:
	$(MAKE) -f CMakeFiles/exempleB.dir/build.make CMakeFiles/exempleB.dir/build
.PHONY : exempleB/fast

#=============================================================================
# Target rules for targets named prog_local_path

# Build rule for target.
prog_local_path: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prog_local_path
.PHONY : prog_local_path

# fast build rule for target.
prog_local_path/fast:
	$(MAKE) -f CMakeFiles/prog_local_path.dir/build.make CMakeFiles/prog_local_path.dir/build
.PHONY : prog_local_path/fast

#=============================================================================
# Target rules for targets named prog_com_microcontroler

# Build rule for target.
prog_com_microcontroler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prog_com_microcontroler
.PHONY : prog_com_microcontroler

# fast build rule for target.
prog_com_microcontroler/fast:
	$(MAKE) -f CMakeFiles/prog_com_microcontroler.dir/build.make CMakeFiles/prog_com_microcontroler.dir/build
.PHONY : prog_com_microcontroler/fast

#=============================================================================
# Target rules for targets named sioclient

# Build rule for target.
sioclient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sioclient
.PHONY : sioclient

# fast build rule for target.
sioclient/fast:
	$(MAKE) -f CMakeFiles/sioclient.dir/build.make CMakeFiles/sioclient.dir/build
.PHONY : sioclient/fast

#=============================================================================
# Target rules for targets named prog_vslam

# Build rule for target.
prog_vslam: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prog_vslam
.PHONY : prog_vslam

# fast build rule for target.
prog_vslam/fast:
	$(MAKE) -f CMakeFiles/prog_vslam.dir/build.make CMakeFiles/prog_vslam.dir/build
.PHONY : prog_vslam/fast

#=============================================================================
# Target rules for targets named sioclient_tls

# Build rule for target.
sioclient_tls: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sioclient_tls
.PHONY : sioclient_tls

# fast build rule for target.
sioclient_tls/fast:
	$(MAKE) -f CMakeFiles/sioclient_tls.dir/build.make CMakeFiles/sioclient_tls.dir/build
.PHONY : sioclient_tls/fast

#=============================================================================
# Target rules for targets named prog_debug

# Build rule for target.
prog_debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prog_debug
.PHONY : prog_debug

# fast build rule for target.
prog_debug/fast:
	$(MAKE) -f CMakeFiles/prog_debug.dir/build.make CMakeFiles/prog_debug.dir/build
.PHONY : prog_debug/fast

software/exempleA.o: software/exempleA.cpp.o

.PHONY : software/exempleA.o

# target to build an object file
software/exempleA.cpp.o:
	$(MAKE) -f CMakeFiles/exempleA.dir/build.make CMakeFiles/exempleA.dir/software/exempleA.cpp.o
.PHONY : software/exempleA.cpp.o

software/exempleA.i: software/exempleA.cpp.i

.PHONY : software/exempleA.i

# target to preprocess a source file
software/exempleA.cpp.i:
	$(MAKE) -f CMakeFiles/exempleA.dir/build.make CMakeFiles/exempleA.dir/software/exempleA.cpp.i
.PHONY : software/exempleA.cpp.i

software/exempleA.s: software/exempleA.cpp.s

.PHONY : software/exempleA.s

# target to generate assembly for a file
software/exempleA.cpp.s:
	$(MAKE) -f CMakeFiles/exempleA.dir/build.make CMakeFiles/exempleA.dir/software/exempleA.cpp.s
.PHONY : software/exempleA.cpp.s

software/exempleB.o: software/exempleB.cpp.o

.PHONY : software/exempleB.o

# target to build an object file
software/exempleB.cpp.o:
	$(MAKE) -f CMakeFiles/exempleB.dir/build.make CMakeFiles/exempleB.dir/software/exempleB.cpp.o
.PHONY : software/exempleB.cpp.o

software/exempleB.i: software/exempleB.cpp.i

.PHONY : software/exempleB.i

# target to preprocess a source file
software/exempleB.cpp.i:
	$(MAKE) -f CMakeFiles/exempleB.dir/build.make CMakeFiles/exempleB.dir/software/exempleB.cpp.i
.PHONY : software/exempleB.cpp.i

software/exempleB.s: software/exempleB.cpp.s

.PHONY : software/exempleB.s

# target to generate assembly for a file
software/exempleB.cpp.s:
	$(MAKE) -f CMakeFiles/exempleB.dir/build.make CMakeFiles/exempleB.dir/software/exempleB.cpp.s
.PHONY : software/exempleB.cpp.s

software/prog_com_microcontroler.o: software/prog_com_microcontroler.cpp.o

.PHONY : software/prog_com_microcontroler.o

# target to build an object file
software/prog_com_microcontroler.cpp.o:
	$(MAKE) -f CMakeFiles/prog_com_microcontroler.dir/build.make CMakeFiles/prog_com_microcontroler.dir/software/prog_com_microcontroler.cpp.o
.PHONY : software/prog_com_microcontroler.cpp.o

software/prog_com_microcontroler.i: software/prog_com_microcontroler.cpp.i

.PHONY : software/prog_com_microcontroler.i

# target to preprocess a source file
software/prog_com_microcontroler.cpp.i:
	$(MAKE) -f CMakeFiles/prog_com_microcontroler.dir/build.make CMakeFiles/prog_com_microcontroler.dir/software/prog_com_microcontroler.cpp.i
.PHONY : software/prog_com_microcontroler.cpp.i

software/prog_com_microcontroler.s: software/prog_com_microcontroler.cpp.s

.PHONY : software/prog_com_microcontroler.s

# target to generate assembly for a file
software/prog_com_microcontroler.cpp.s:
	$(MAKE) -f CMakeFiles/prog_com_microcontroler.dir/build.make CMakeFiles/prog_com_microcontroler.dir/software/prog_com_microcontroler.cpp.s
.PHONY : software/prog_com_microcontroler.cpp.s

software/prog_com_server.o: software/prog_com_server.cpp.o

.PHONY : software/prog_com_server.o

# target to build an object file
software/prog_com_server.cpp.o:
	$(MAKE) -f CMakeFiles/prog_com_server.dir/build.make CMakeFiles/prog_com_server.dir/software/prog_com_server.cpp.o
.PHONY : software/prog_com_server.cpp.o

software/prog_com_server.i: software/prog_com_server.cpp.i

.PHONY : software/prog_com_server.i

# target to preprocess a source file
software/prog_com_server.cpp.i:
	$(MAKE) -f CMakeFiles/prog_com_server.dir/build.make CMakeFiles/prog_com_server.dir/software/prog_com_server.cpp.i
.PHONY : software/prog_com_server.cpp.i

software/prog_com_server.s: software/prog_com_server.cpp.s

.PHONY : software/prog_com_server.s

# target to generate assembly for a file
software/prog_com_server.cpp.s:
	$(MAKE) -f CMakeFiles/prog_com_server.dir/build.make CMakeFiles/prog_com_server.dir/software/prog_com_server.cpp.s
.PHONY : software/prog_com_server.cpp.s

software/prog_data_manager.o: software/prog_data_manager.cpp.o

.PHONY : software/prog_data_manager.o

# target to build an object file
software/prog_data_manager.cpp.o:
	$(MAKE) -f CMakeFiles/prog_data_manager.dir/build.make CMakeFiles/prog_data_manager.dir/software/prog_data_manager.cpp.o
.PHONY : software/prog_data_manager.cpp.o

software/prog_data_manager.i: software/prog_data_manager.cpp.i

.PHONY : software/prog_data_manager.i

# target to preprocess a source file
software/prog_data_manager.cpp.i:
	$(MAKE) -f CMakeFiles/prog_data_manager.dir/build.make CMakeFiles/prog_data_manager.dir/software/prog_data_manager.cpp.i
.PHONY : software/prog_data_manager.cpp.i

software/prog_data_manager.s: software/prog_data_manager.cpp.s

.PHONY : software/prog_data_manager.s

# target to generate assembly for a file
software/prog_data_manager.cpp.s:
	$(MAKE) -f CMakeFiles/prog_data_manager.dir/build.make CMakeFiles/prog_data_manager.dir/software/prog_data_manager.cpp.s
.PHONY : software/prog_data_manager.cpp.s

software/prog_debug.o: software/prog_debug.cpp.o

.PHONY : software/prog_debug.o

# target to build an object file
software/prog_debug.cpp.o:
	$(MAKE) -f CMakeFiles/prog_debug.dir/build.make CMakeFiles/prog_debug.dir/software/prog_debug.cpp.o
.PHONY : software/prog_debug.cpp.o

software/prog_debug.i: software/prog_debug.cpp.i

.PHONY : software/prog_debug.i

# target to preprocess a source file
software/prog_debug.cpp.i:
	$(MAKE) -f CMakeFiles/prog_debug.dir/build.make CMakeFiles/prog_debug.dir/software/prog_debug.cpp.i
.PHONY : software/prog_debug.cpp.i

software/prog_debug.s: software/prog_debug.cpp.s

.PHONY : software/prog_debug.s

# target to generate assembly for a file
software/prog_debug.cpp.s:
	$(MAKE) -f CMakeFiles/prog_debug.dir/build.make CMakeFiles/prog_debug.dir/software/prog_debug.cpp.s
.PHONY : software/prog_debug.cpp.s

software/prog_global_path.o: software/prog_global_path.cpp.o

.PHONY : software/prog_global_path.o

# target to build an object file
software/prog_global_path.cpp.o:
	$(MAKE) -f CMakeFiles/prog_global_path.dir/build.make CMakeFiles/prog_global_path.dir/software/prog_global_path.cpp.o
.PHONY : software/prog_global_path.cpp.o

software/prog_global_path.i: software/prog_global_path.cpp.i

.PHONY : software/prog_global_path.i

# target to preprocess a source file
software/prog_global_path.cpp.i:
	$(MAKE) -f CMakeFiles/prog_global_path.dir/build.make CMakeFiles/prog_global_path.dir/software/prog_global_path.cpp.i
.PHONY : software/prog_global_path.cpp.i

software/prog_global_path.s: software/prog_global_path.cpp.s

.PHONY : software/prog_global_path.s

# target to generate assembly for a file
software/prog_global_path.cpp.s:
	$(MAKE) -f CMakeFiles/prog_global_path.dir/build.make CMakeFiles/prog_global_path.dir/software/prog_global_path.cpp.s
.PHONY : software/prog_global_path.cpp.s

software/prog_lidar.o: software/prog_lidar.cpp.o

.PHONY : software/prog_lidar.o

# target to build an object file
software/prog_lidar.cpp.o:
	$(MAKE) -f CMakeFiles/prog_lidar.dir/build.make CMakeFiles/prog_lidar.dir/software/prog_lidar.cpp.o
.PHONY : software/prog_lidar.cpp.o

software/prog_lidar.i: software/prog_lidar.cpp.i

.PHONY : software/prog_lidar.i

# target to preprocess a source file
software/prog_lidar.cpp.i:
	$(MAKE) -f CMakeFiles/prog_lidar.dir/build.make CMakeFiles/prog_lidar.dir/software/prog_lidar.cpp.i
.PHONY : software/prog_lidar.cpp.i

software/prog_lidar.s: software/prog_lidar.cpp.s

.PHONY : software/prog_lidar.s

# target to generate assembly for a file
software/prog_lidar.cpp.s:
	$(MAKE) -f CMakeFiles/prog_lidar.dir/build.make CMakeFiles/prog_lidar.dir/software/prog_lidar.cpp.s
.PHONY : software/prog_lidar.cpp.s

software/prog_local_path.o: software/prog_local_path.cpp.o

.PHONY : software/prog_local_path.o

# target to build an object file
software/prog_local_path.cpp.o:
	$(MAKE) -f CMakeFiles/prog_local_path.dir/build.make CMakeFiles/prog_local_path.dir/software/prog_local_path.cpp.o
.PHONY : software/prog_local_path.cpp.o

software/prog_local_path.i: software/prog_local_path.cpp.i

.PHONY : software/prog_local_path.i

# target to preprocess a source file
software/prog_local_path.cpp.i:
	$(MAKE) -f CMakeFiles/prog_local_path.dir/build.make CMakeFiles/prog_local_path.dir/software/prog_local_path.cpp.i
.PHONY : software/prog_local_path.cpp.i

software/prog_local_path.s: software/prog_local_path.cpp.s

.PHONY : software/prog_local_path.s

# target to generate assembly for a file
software/prog_local_path.cpp.s:
	$(MAKE) -f CMakeFiles/prog_local_path.dir/build.make CMakeFiles/prog_local_path.dir/software/prog_local_path.cpp.s
.PHONY : software/prog_local_path.cpp.s

software/prog_vslam.o: software/prog_vslam.cpp.o

.PHONY : software/prog_vslam.o

# target to build an object file
software/prog_vslam.cpp.o:
	$(MAKE) -f CMakeFiles/prog_vslam.dir/build.make CMakeFiles/prog_vslam.dir/software/prog_vslam.cpp.o
.PHONY : software/prog_vslam.cpp.o

software/prog_vslam.i: software/prog_vslam.cpp.i

.PHONY : software/prog_vslam.i

# target to preprocess a source file
software/prog_vslam.cpp.i:
	$(MAKE) -f CMakeFiles/prog_vslam.dir/build.make CMakeFiles/prog_vslam.dir/software/prog_vslam.cpp.i
.PHONY : software/prog_vslam.cpp.i

software/prog_vslam.s: software/prog_vslam.cpp.s

.PHONY : software/prog_vslam.s

# target to generate assembly for a file
software/prog_vslam.cpp.s:
	$(MAKE) -f CMakeFiles/prog_vslam.dir/build.make CMakeFiles/prog_vslam.dir/software/prog_vslam.cpp.s
.PHONY : software/prog_vslam.cpp.s

src/com_micro_lib.o: src/com_micro_lib.cpp.o

.PHONY : src/com_micro_lib.o

# target to build an object file
src/com_micro_lib.cpp.o:
	$(MAKE) -f CMakeFiles/prog_com_microcontroler.dir/build.make CMakeFiles/prog_com_microcontroler.dir/src/com_micro_lib.cpp.o
.PHONY : src/com_micro_lib.cpp.o

src/com_micro_lib.i: src/com_micro_lib.cpp.i

.PHONY : src/com_micro_lib.i

# target to preprocess a source file
src/com_micro_lib.cpp.i:
	$(MAKE) -f CMakeFiles/prog_com_microcontroler.dir/build.make CMakeFiles/prog_com_microcontroler.dir/src/com_micro_lib.cpp.i
.PHONY : src/com_micro_lib.cpp.i

src/com_micro_lib.s: src/com_micro_lib.cpp.s

.PHONY : src/com_micro_lib.s

# target to generate assembly for a file
src/com_micro_lib.cpp.s:
	$(MAKE) -f CMakeFiles/prog_com_microcontroler.dir/build.make CMakeFiles/prog_com_microcontroler.dir/src/com_micro_lib.cpp.s
.PHONY : src/com_micro_lib.cpp.s

src/com_server_lib.o: src/com_server_lib.cpp.o

.PHONY : src/com_server_lib.o

# target to build an object file
src/com_server_lib.cpp.o:
	$(MAKE) -f CMakeFiles/prog_com_server.dir/build.make CMakeFiles/prog_com_server.dir/src/com_server_lib.cpp.o
.PHONY : src/com_server_lib.cpp.o

src/com_server_lib.i: src/com_server_lib.cpp.i

.PHONY : src/com_server_lib.i

# target to preprocess a source file
src/com_server_lib.cpp.i:
	$(MAKE) -f CMakeFiles/prog_com_server.dir/build.make CMakeFiles/prog_com_server.dir/src/com_server_lib.cpp.i
.PHONY : src/com_server_lib.cpp.i

src/com_server_lib.s: src/com_server_lib.cpp.s

.PHONY : src/com_server_lib.s

# target to generate assembly for a file
src/com_server_lib.cpp.s:
	$(MAKE) -f CMakeFiles/prog_com_server.dir/build.make CMakeFiles/prog_com_server.dir/src/com_server_lib.cpp.s
.PHONY : src/com_server_lib.cpp.s

src/global_path_lib.o: src/global_path_lib.cpp.o

.PHONY : src/global_path_lib.o

# target to build an object file
src/global_path_lib.cpp.o:
	$(MAKE) -f CMakeFiles/prog_global_path.dir/build.make CMakeFiles/prog_global_path.dir/src/global_path_lib.cpp.o
	$(MAKE) -f CMakeFiles/prog_local_path.dir/build.make CMakeFiles/prog_local_path.dir/src/global_path_lib.cpp.o
.PHONY : src/global_path_lib.cpp.o

src/global_path_lib.i: src/global_path_lib.cpp.i

.PHONY : src/global_path_lib.i

# target to preprocess a source file
src/global_path_lib.cpp.i:
	$(MAKE) -f CMakeFiles/prog_global_path.dir/build.make CMakeFiles/prog_global_path.dir/src/global_path_lib.cpp.i
	$(MAKE) -f CMakeFiles/prog_local_path.dir/build.make CMakeFiles/prog_local_path.dir/src/global_path_lib.cpp.i
.PHONY : src/global_path_lib.cpp.i

src/global_path_lib.s: src/global_path_lib.cpp.s

.PHONY : src/global_path_lib.s

# target to generate assembly for a file
src/global_path_lib.cpp.s:
	$(MAKE) -f CMakeFiles/prog_global_path.dir/build.make CMakeFiles/prog_global_path.dir/src/global_path_lib.cpp.s
	$(MAKE) -f CMakeFiles/prog_local_path.dir/build.make CMakeFiles/prog_local_path.dir/src/global_path_lib.cpp.s
.PHONY : src/global_path_lib.cpp.s

src/lidar_lib.o: src/lidar_lib.cpp.o

.PHONY : src/lidar_lib.o

# target to build an object file
src/lidar_lib.cpp.o:
	$(MAKE) -f CMakeFiles/prog_lidar.dir/build.make CMakeFiles/prog_lidar.dir/src/lidar_lib.cpp.o
.PHONY : src/lidar_lib.cpp.o

src/lidar_lib.i: src/lidar_lib.cpp.i

.PHONY : src/lidar_lib.i

# target to preprocess a source file
src/lidar_lib.cpp.i:
	$(MAKE) -f CMakeFiles/prog_lidar.dir/build.make CMakeFiles/prog_lidar.dir/src/lidar_lib.cpp.i
.PHONY : src/lidar_lib.cpp.i

src/lidar_lib.s: src/lidar_lib.cpp.s

.PHONY : src/lidar_lib.s

# target to generate assembly for a file
src/lidar_lib.cpp.s:
	$(MAKE) -f CMakeFiles/prog_lidar.dir/build.make CMakeFiles/prog_lidar.dir/src/lidar_lib.cpp.s
.PHONY : src/lidar_lib.cpp.s

src/local_path_lib.o: src/local_path_lib.cpp.o

.PHONY : src/local_path_lib.o

# target to build an object file
src/local_path_lib.cpp.o:
	$(MAKE) -f CMakeFiles/prog_local_path.dir/build.make CMakeFiles/prog_local_path.dir/src/local_path_lib.cpp.o
.PHONY : src/local_path_lib.cpp.o

src/local_path_lib.i: src/local_path_lib.cpp.i

.PHONY : src/local_path_lib.i

# target to preprocess a source file
src/local_path_lib.cpp.i:
	$(MAKE) -f CMakeFiles/prog_local_path.dir/build.make CMakeFiles/prog_local_path.dir/src/local_path_lib.cpp.i
.PHONY : src/local_path_lib.cpp.i

src/local_path_lib.s: src/local_path_lib.cpp.s

.PHONY : src/local_path_lib.s

# target to generate assembly for a file
src/local_path_lib.cpp.s:
	$(MAKE) -f CMakeFiles/prog_local_path.dir/build.make CMakeFiles/prog_local_path.dir/src/local_path_lib.cpp.s
.PHONY : src/local_path_lib.cpp.s

src/manager_lib.o: src/manager_lib.cpp.o

.PHONY : src/manager_lib.o

# target to build an object file
src/manager_lib.cpp.o:
	$(MAKE) -f CMakeFiles/prog_data_manager.dir/build.make CMakeFiles/prog_data_manager.dir/src/manager_lib.cpp.o
.PHONY : src/manager_lib.cpp.o

src/manager_lib.i: src/manager_lib.cpp.i

.PHONY : src/manager_lib.i

# target to preprocess a source file
src/manager_lib.cpp.i:
	$(MAKE) -f CMakeFiles/prog_data_manager.dir/build.make CMakeFiles/prog_data_manager.dir/src/manager_lib.cpp.i
.PHONY : src/manager_lib.cpp.i

src/manager_lib.s: src/manager_lib.cpp.s

.PHONY : src/manager_lib.s

# target to generate assembly for a file
src/manager_lib.cpp.s:
	$(MAKE) -f CMakeFiles/prog_data_manager.dir/build.make CMakeFiles/prog_data_manager.dir/src/manager_lib.cpp.s
.PHONY : src/manager_lib.cpp.s

src/vslam_lib.o: src/vslam_lib.cpp.o

.PHONY : src/vslam_lib.o

# target to build an object file
src/vslam_lib.cpp.o:
	$(MAKE) -f CMakeFiles/prog_vslam.dir/build.make CMakeFiles/prog_vslam.dir/src/vslam_lib.cpp.o
.PHONY : src/vslam_lib.cpp.o

src/vslam_lib.i: src/vslam_lib.cpp.i

.PHONY : src/vslam_lib.i

# target to preprocess a source file
src/vslam_lib.cpp.i:
	$(MAKE) -f CMakeFiles/prog_vslam.dir/build.make CMakeFiles/prog_vslam.dir/src/vslam_lib.cpp.i
.PHONY : src/vslam_lib.cpp.i

src/vslam_lib.s: src/vslam_lib.cpp.s

.PHONY : src/vslam_lib.s

# target to generate assembly for a file
src/vslam_lib.cpp.s:
	$(MAKE) -f CMakeFiles/prog_vslam.dir/build.make CMakeFiles/prog_vslam.dir/src/vslam_lib.cpp.s
.PHONY : src/vslam_lib.cpp.s

thirdparty/socket.io-client-cpp/src/internal/sio_client_impl.o: thirdparty/socket.io-client-cpp/src/internal/sio_client_impl.cpp.o

.PHONY : thirdparty/socket.io-client-cpp/src/internal/sio_client_impl.o

# target to build an object file
thirdparty/socket.io-client-cpp/src/internal/sio_client_impl.cpp.o:
	$(MAKE) -f CMakeFiles/sioclient.dir/build.make CMakeFiles/sioclient.dir/thirdparty/socket.io-client-cpp/src/internal/sio_client_impl.cpp.o
	$(MAKE) -f CMakeFiles/sioclient_tls.dir/build.make CMakeFiles/sioclient_tls.dir/thirdparty/socket.io-client-cpp/src/internal/sio_client_impl.cpp.o
.PHONY : thirdparty/socket.io-client-cpp/src/internal/sio_client_impl.cpp.o

thirdparty/socket.io-client-cpp/src/internal/sio_client_impl.i: thirdparty/socket.io-client-cpp/src/internal/sio_client_impl.cpp.i

.PHONY : thirdparty/socket.io-client-cpp/src/internal/sio_client_impl.i

# target to preprocess a source file
thirdparty/socket.io-client-cpp/src/internal/sio_client_impl.cpp.i:
	$(MAKE) -f CMakeFiles/sioclient.dir/build.make CMakeFiles/sioclient.dir/thirdparty/socket.io-client-cpp/src/internal/sio_client_impl.cpp.i
	$(MAKE) -f CMakeFiles/sioclient_tls.dir/build.make CMakeFiles/sioclient_tls.dir/thirdparty/socket.io-client-cpp/src/internal/sio_client_impl.cpp.i
.PHONY : thirdparty/socket.io-client-cpp/src/internal/sio_client_impl.cpp.i

thirdparty/socket.io-client-cpp/src/internal/sio_client_impl.s: thirdparty/socket.io-client-cpp/src/internal/sio_client_impl.cpp.s

.PHONY : thirdparty/socket.io-client-cpp/src/internal/sio_client_impl.s

# target to generate assembly for a file
thirdparty/socket.io-client-cpp/src/internal/sio_client_impl.cpp.s:
	$(MAKE) -f CMakeFiles/sioclient.dir/build.make CMakeFiles/sioclient.dir/thirdparty/socket.io-client-cpp/src/internal/sio_client_impl.cpp.s
	$(MAKE) -f CMakeFiles/sioclient_tls.dir/build.make CMakeFiles/sioclient_tls.dir/thirdparty/socket.io-client-cpp/src/internal/sio_client_impl.cpp.s
.PHONY : thirdparty/socket.io-client-cpp/src/internal/sio_client_impl.cpp.s

thirdparty/socket.io-client-cpp/src/internal/sio_packet.o: thirdparty/socket.io-client-cpp/src/internal/sio_packet.cpp.o

.PHONY : thirdparty/socket.io-client-cpp/src/internal/sio_packet.o

# target to build an object file
thirdparty/socket.io-client-cpp/src/internal/sio_packet.cpp.o:
	$(MAKE) -f CMakeFiles/sioclient.dir/build.make CMakeFiles/sioclient.dir/thirdparty/socket.io-client-cpp/src/internal/sio_packet.cpp.o
	$(MAKE) -f CMakeFiles/sioclient_tls.dir/build.make CMakeFiles/sioclient_tls.dir/thirdparty/socket.io-client-cpp/src/internal/sio_packet.cpp.o
.PHONY : thirdparty/socket.io-client-cpp/src/internal/sio_packet.cpp.o

thirdparty/socket.io-client-cpp/src/internal/sio_packet.i: thirdparty/socket.io-client-cpp/src/internal/sio_packet.cpp.i

.PHONY : thirdparty/socket.io-client-cpp/src/internal/sio_packet.i

# target to preprocess a source file
thirdparty/socket.io-client-cpp/src/internal/sio_packet.cpp.i:
	$(MAKE) -f CMakeFiles/sioclient.dir/build.make CMakeFiles/sioclient.dir/thirdparty/socket.io-client-cpp/src/internal/sio_packet.cpp.i
	$(MAKE) -f CMakeFiles/sioclient_tls.dir/build.make CMakeFiles/sioclient_tls.dir/thirdparty/socket.io-client-cpp/src/internal/sio_packet.cpp.i
.PHONY : thirdparty/socket.io-client-cpp/src/internal/sio_packet.cpp.i

thirdparty/socket.io-client-cpp/src/internal/sio_packet.s: thirdparty/socket.io-client-cpp/src/internal/sio_packet.cpp.s

.PHONY : thirdparty/socket.io-client-cpp/src/internal/sio_packet.s

# target to generate assembly for a file
thirdparty/socket.io-client-cpp/src/internal/sio_packet.cpp.s:
	$(MAKE) -f CMakeFiles/sioclient.dir/build.make CMakeFiles/sioclient.dir/thirdparty/socket.io-client-cpp/src/internal/sio_packet.cpp.s
	$(MAKE) -f CMakeFiles/sioclient_tls.dir/build.make CMakeFiles/sioclient_tls.dir/thirdparty/socket.io-client-cpp/src/internal/sio_packet.cpp.s
.PHONY : thirdparty/socket.io-client-cpp/src/internal/sio_packet.cpp.s

thirdparty/socket.io-client-cpp/src/sio_client.o: thirdparty/socket.io-client-cpp/src/sio_client.cpp.o

.PHONY : thirdparty/socket.io-client-cpp/src/sio_client.o

# target to build an object file
thirdparty/socket.io-client-cpp/src/sio_client.cpp.o:
	$(MAKE) -f CMakeFiles/sioclient.dir/build.make CMakeFiles/sioclient.dir/thirdparty/socket.io-client-cpp/src/sio_client.cpp.o
	$(MAKE) -f CMakeFiles/sioclient_tls.dir/build.make CMakeFiles/sioclient_tls.dir/thirdparty/socket.io-client-cpp/src/sio_client.cpp.o
.PHONY : thirdparty/socket.io-client-cpp/src/sio_client.cpp.o

thirdparty/socket.io-client-cpp/src/sio_client.i: thirdparty/socket.io-client-cpp/src/sio_client.cpp.i

.PHONY : thirdparty/socket.io-client-cpp/src/sio_client.i

# target to preprocess a source file
thirdparty/socket.io-client-cpp/src/sio_client.cpp.i:
	$(MAKE) -f CMakeFiles/sioclient.dir/build.make CMakeFiles/sioclient.dir/thirdparty/socket.io-client-cpp/src/sio_client.cpp.i
	$(MAKE) -f CMakeFiles/sioclient_tls.dir/build.make CMakeFiles/sioclient_tls.dir/thirdparty/socket.io-client-cpp/src/sio_client.cpp.i
.PHONY : thirdparty/socket.io-client-cpp/src/sio_client.cpp.i

thirdparty/socket.io-client-cpp/src/sio_client.s: thirdparty/socket.io-client-cpp/src/sio_client.cpp.s

.PHONY : thirdparty/socket.io-client-cpp/src/sio_client.s

# target to generate assembly for a file
thirdparty/socket.io-client-cpp/src/sio_client.cpp.s:
	$(MAKE) -f CMakeFiles/sioclient.dir/build.make CMakeFiles/sioclient.dir/thirdparty/socket.io-client-cpp/src/sio_client.cpp.s
	$(MAKE) -f CMakeFiles/sioclient_tls.dir/build.make CMakeFiles/sioclient_tls.dir/thirdparty/socket.io-client-cpp/src/sio_client.cpp.s
.PHONY : thirdparty/socket.io-client-cpp/src/sio_client.cpp.s

thirdparty/socket.io-client-cpp/src/sio_socket.o: thirdparty/socket.io-client-cpp/src/sio_socket.cpp.o

.PHONY : thirdparty/socket.io-client-cpp/src/sio_socket.o

# target to build an object file
thirdparty/socket.io-client-cpp/src/sio_socket.cpp.o:
	$(MAKE) -f CMakeFiles/sioclient.dir/build.make CMakeFiles/sioclient.dir/thirdparty/socket.io-client-cpp/src/sio_socket.cpp.o
	$(MAKE) -f CMakeFiles/sioclient_tls.dir/build.make CMakeFiles/sioclient_tls.dir/thirdparty/socket.io-client-cpp/src/sio_socket.cpp.o
.PHONY : thirdparty/socket.io-client-cpp/src/sio_socket.cpp.o

thirdparty/socket.io-client-cpp/src/sio_socket.i: thirdparty/socket.io-client-cpp/src/sio_socket.cpp.i

.PHONY : thirdparty/socket.io-client-cpp/src/sio_socket.i

# target to preprocess a source file
thirdparty/socket.io-client-cpp/src/sio_socket.cpp.i:
	$(MAKE) -f CMakeFiles/sioclient.dir/build.make CMakeFiles/sioclient.dir/thirdparty/socket.io-client-cpp/src/sio_socket.cpp.i
	$(MAKE) -f CMakeFiles/sioclient_tls.dir/build.make CMakeFiles/sioclient_tls.dir/thirdparty/socket.io-client-cpp/src/sio_socket.cpp.i
.PHONY : thirdparty/socket.io-client-cpp/src/sio_socket.cpp.i

thirdparty/socket.io-client-cpp/src/sio_socket.s: thirdparty/socket.io-client-cpp/src/sio_socket.cpp.s

.PHONY : thirdparty/socket.io-client-cpp/src/sio_socket.s

# target to generate assembly for a file
thirdparty/socket.io-client-cpp/src/sio_socket.cpp.s:
	$(MAKE) -f CMakeFiles/sioclient.dir/build.make CMakeFiles/sioclient.dir/thirdparty/socket.io-client-cpp/src/sio_socket.cpp.s
	$(MAKE) -f CMakeFiles/sioclient_tls.dir/build.make CMakeFiles/sioclient_tls.dir/thirdparty/socket.io-client-cpp/src/sio_socket.cpp.s
.PHONY : thirdparty/socket.io-client-cpp/src/sio_socket.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... prog_lidar"
	@echo "... prog_com_server"
	@echo "... prog_global_path"
	@echo "... exempleA"
	@echo "... install/local"
	@echo "... prog_data_manager"
	@echo "... install"
	@echo "... install/strip"
	@echo "... exempleB"
	@echo "... prog_local_path"
	@echo "... prog_com_microcontroler"
	@echo "... sioclient"
	@echo "... prog_vslam"
	@echo "... rebuild_cache"
	@echo "... sioclient_tls"
	@echo "... prog_debug"
	@echo "... edit_cache"
	@echo "... list_install_components"
	@echo "... software/exempleA.o"
	@echo "... software/exempleA.i"
	@echo "... software/exempleA.s"
	@echo "... software/exempleB.o"
	@echo "... software/exempleB.i"
	@echo "... software/exempleB.s"
	@echo "... software/prog_com_microcontroler.o"
	@echo "... software/prog_com_microcontroler.i"
	@echo "... software/prog_com_microcontroler.s"
	@echo "... software/prog_com_server.o"
	@echo "... software/prog_com_server.i"
	@echo "... software/prog_com_server.s"
	@echo "... software/prog_data_manager.o"
	@echo "... software/prog_data_manager.i"
	@echo "... software/prog_data_manager.s"
	@echo "... software/prog_debug.o"
	@echo "... software/prog_debug.i"
	@echo "... software/prog_debug.s"
	@echo "... software/prog_global_path.o"
	@echo "... software/prog_global_path.i"
	@echo "... software/prog_global_path.s"
	@echo "... software/prog_lidar.o"
	@echo "... software/prog_lidar.i"
	@echo "... software/prog_lidar.s"
	@echo "... software/prog_local_path.o"
	@echo "... software/prog_local_path.i"
	@echo "... software/prog_local_path.s"
	@echo "... software/prog_vslam.o"
	@echo "... software/prog_vslam.i"
	@echo "... software/prog_vslam.s"
	@echo "... src/com_micro_lib.o"
	@echo "... src/com_micro_lib.i"
	@echo "... src/com_micro_lib.s"
	@echo "... src/com_server_lib.o"
	@echo "... src/com_server_lib.i"
	@echo "... src/com_server_lib.s"
	@echo "... src/global_path_lib.o"
	@echo "... src/global_path_lib.i"
	@echo "... src/global_path_lib.s"
	@echo "... src/lidar_lib.o"
	@echo "... src/lidar_lib.i"
	@echo "... src/lidar_lib.s"
	@echo "... src/local_path_lib.o"
	@echo "... src/local_path_lib.i"
	@echo "... src/local_path_lib.s"
	@echo "... src/manager_lib.o"
	@echo "... src/manager_lib.i"
	@echo "... src/manager_lib.s"
	@echo "... src/vslam_lib.o"
	@echo "... src/vslam_lib.i"
	@echo "... src/vslam_lib.s"
	@echo "... thirdparty/socket.io-client-cpp/src/internal/sio_client_impl.o"
	@echo "... thirdparty/socket.io-client-cpp/src/internal/sio_client_impl.i"
	@echo "... thirdparty/socket.io-client-cpp/src/internal/sio_client_impl.s"
	@echo "... thirdparty/socket.io-client-cpp/src/internal/sio_packet.o"
	@echo "... thirdparty/socket.io-client-cpp/src/internal/sio_packet.i"
	@echo "... thirdparty/socket.io-client-cpp/src/internal/sio_packet.s"
	@echo "... thirdparty/socket.io-client-cpp/src/sio_client.o"
	@echo "... thirdparty/socket.io-client-cpp/src/sio_client.i"
	@echo "... thirdparty/socket.io-client-cpp/src/sio_client.s"
	@echo "... thirdparty/socket.io-client-cpp/src/sio_socket.o"
	@echo "... thirdparty/socket.io-client-cpp/src/sio_socket.i"
	@echo "... thirdparty/socket.io-client-cpp/src/sio_socket.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

